name: Deploy App on Dev Env

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    
    - id: auth
      uses: 'google-github-actions/auth@v2'
      with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0

    - name: Set crdential_file
      run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}

    - name: Deploy to GCP VM
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_VM_SSH_KEY }}
        script: |
          sudo gcloud auth configure-docker europe-west9-docker.pkg.dev --quiet
          sudo docker compose pull
          sudo docker compose up -d
          
