name: Deploy App on Dev Env

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: Authenticate Docker with GCR
      run: |
        gcloud auth configure-docker europe-west9-docker.pkg.dev

    - name: Deploy to GCP VM
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_VM_SSH_KEY }}
        script: |
          sudo touch new.py
          
